class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    '繁體中文': {
      'app_title': 'SumoBee',
      'settings_title': '系統設定',
      'preferences': '偏好設定',
      'app_language': 'App 顯示語言',
      'output_language': '總結輸出語言',
      'summary_length': '摘要長度',
      'ultra_short': '極簡 (Ultra-short)',
      'concise': '精簡 (Concise)',
      'detailed': '詳細 (Detailed)',
      'maintenance': '維護',
      'clear_all_data': '清除所有資料',
      'remove_data_desc': '移除 API 金鑰與快取設定',
      'about': '關於',
      'version': '版本號',
      'groq_settings': 'Groq API 設定',
      'get_api_key': '申請金鑰',
      'auto_fill_desc': '複製金鑰後回到 App 會自動偵測填入',
      'instant_summary': '即刻摘要',
      'paste_url': '貼上 YouTube 影片網址...',
      'start_generation': '開始 AI 生成',
      'history': '摘要紀錄',
      'guide': '操作指南',
      'guide_step1': '在 YouTube 點擊「分享」',
      'guide_step2': '清單中選擇「SumoBee」',
      'guide_step3': '等待 30 秒即可獲得精華摘要',
      'summarizing': 'SumoBee 正在努力摘要中...',
      'clear_success': '✅ 資料已清除',
      'clear_confirm_title': '全部清除？',
      'clear_confirm_content': '這將會移除所有儲存的 API 金鑰與設定。',
      'cancel': '取消',
      'confirm_clear': '確認清除',
      'share_results': '分享結果',
      'copy_text': '複製文字',
      'send_email': '發送郵件',
      'summary_preview': '摘要內容',
    },
    'English': {
      'app_title': 'SumoBee',
      'settings_title': 'Settings',
      'preferences': 'Preferences',
      'app_language': 'App Display Language',
      'output_language': 'Summary Output Language',
      'summary_length': 'Summary Length',
      'ultra_short': 'Ultra-short',
      'concise': 'Concise',
      'detailed': 'Detailed',
      'maintenance': 'Maintenance',
      'clear_all_data': 'Clear All Data',
      'remove_data_desc': 'Remove API keys and settings',
      'about': 'About',
      'version': 'Version',
      'groq_settings': 'Groq API Settings',
      'get_api_key': 'Get Key',
      'auto_fill_desc': 'Auto-detected after copying your key',
      'instant_summary': 'Instant Summary',
      'paste_url': 'Paste YouTube video URL...',
      'start_generation': 'Start AI Generation',
      'history': 'History',
      'guide': 'Guide',
      'guide_step1': 'Click "Share" on YouTube',
      'guide_step2': 'Select "SumoBee" from list',
      'guide_step3': 'Wait 30s for your summary',
      'summarizing': 'SumoBee is summarizing...',
      'clear_success': '✅ Data cleared',
      'clear_confirm_title': 'Clear All?',
      'clear_confirm_content': 'This will remove all saved API keys and settings.',
      'cancel': 'Cancel',
      'confirm_clear': 'Clear',
      'share_results': 'Share Results',
      'copy_text': 'Copy Text',
      'send_email': 'Send Email',
      'summary_preview': 'Summary',
    },
    '日本語': {
      'app_title': 'SumoBee',
      'settings_title': '設定',
      'preferences': '詳細設定',
      'app_language': '表示言語',
      'output_language': '出力言語',
      'summary_length': '要約の長さ',
      'ultra_short': '最短 (Ultra-short)',
      'concise': '簡潔 (Concise)',
      'detailed': '詳細 (Detailed)',
      'maintenance': 'メンテナンス',
      'clear_all_data': 'すべてのデータを削除',
      'remove_data_desc': 'APIキーと設定を削除します',
      'about': '製品について',
      'version': 'バージョン',
      'groq_settings': 'Groq API 設定',
      'get_api_key': 'キーを取得',
      'auto_fill_desc': 'キーをコピーすると自動的に入力されます',
      'instant_summary': '今すぐ要約',
      'paste_url': 'YouTube動画のURLを貼り付け...',
      'start_generation': 'AI生成を開始',
      'history': '履歴',
      'guide': 'ガイド',
      'guide_step1': 'YouTubeで「共有」をクリック',
      'guide_step2': 'リストから「SumoBee」を選択',
      'guide_step3': '30秒ほどで要約が完成します',
      'summarizing': 'SumoBeeが要約しています...',
      'clear_success': '✅ データを削除しました',
      'clear_confirm_title': '削除しますか？',
      'clear_confirm_content': '保存されたすべてのキーと設定が削除されます。',
      'cancel': 'キャンセル',
      'confirm_clear': '削除',
      'share_results': '結果を共有',
      'copy_text': 'テキストをコピー',
      'send_email': 'メールを送信',
      'summary_preview': '要約内容',
    },
    '한국어': {
      'app_title': 'SumoBee',
      'settings_title': '시스템 설정',
      'preferences': '환경 설정',
      'app_language': '앱 표시 언어',
      'output_language': '요약 출력 언어',
      'summary_length': '요약 길이',
      'ultra_short': '매우 짧게 (Ultra-short)',
      'concise': '간결하게 (Concise)',
      'detailed': '자세하게 (Detailed)',
      'maintenance': '유지 관리',
      'clear_all_data': '모든 데이터 삭제',
      'remove_data_desc': 'API 키와 설정을 삭제합니다',
      'about': '정보',
      'version': '버전',
      'groq_settings': 'Groq API 설정',
      'get_api_key': '키 발급받기',
      'auto_fill_desc': '키를 복사하면 자동으로 입력됩니다',
      'instant_summary': '즉시 요약',
      'paste_url': 'YouTube 동 영상 URL 붙여넣기...',
      'start_generation': 'AI 생성 시작',
      'history': '히스토리',
      'guide': '사용 안내',
      'guide_step1': 'YouTube에서 "공유" 클릭',
      'guide_step2': '목록에서 "SumoBee" 선택',
      'guide_step3': '30초만 기다리면 요약 완성!',
      'summarizing': 'SumoBee가 요약 중입니다...',
      'clear_success': '✅ 데이터가 삭제되었습니다',
      'clear_confirm_title': '모두 삭제하시겠습니까?',
      'clear_confirm_content': '저장된 모든 API 키와 설정이 삭제됩니다.',
      'cancel': '취소',
      'confirm_clear': '삭제 확인',
      'share_results': '결과 공유',
      'copy_text': '텍스트 복사',
      'send_email': '이메일 전송',
      'summary_preview': '요약 내용',
    }
  };

  static String getString(String key, String language) {
    return _localizedValues[language]?[key] ?? _localizedValues['繁體中文']![key]!;
  }
}
